// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2019-04-03 20:44:50.048496 +0800 CST m=+0.030981280

package docs

import (
	"bytes"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/hash/xiuxiu/v3": {
            "post": {
                "description": "Get a similar result",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "xiuxiu"
                ],
                "summary": "Get a similar result by xiuxiu images retrieval",
                "parameters": [
                    {
                        "description": "Get a similar list",
                        "name": "xiuxiu",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/xiuxiu.GetRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":0,\"message\":\"OK\",\"data\":{\"username\":\"lcx\"}}",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/xiuxiu.GetResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "xiuxiu.GetRequest": {
            "type": "object",
            "properties": {
                "image": {
                    "type": "string"
                },
                "top": {
                    "type": "string"
                }
            }
        },
        "xiuxiu.GetResponse": {
            "type": "object",
            "properties": {
                "image": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo swaggerInfo

type s struct{}

func (s *s) ReadDoc() string {
	t, err := template.New("swagger_info").Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, SwaggerInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
